### ISSUE TITLE
Disadvantage button text jumps out

### ISSUE THREAD

**Issue by a-parent** [krbz999/foundryvtt-retroactive-advantage-5e#2]
the text on the button for disadvantage is too big and jumps on two lines.

<img width="291" alt="Screenshot 2024-02-14 at 13 20 32" src="https://github.com/krbz999/foundryvtt-retroactive-advantage-5e/assets/86935017/96084474-29e9-4c5c-9f2a-cc93f2821d61">

**Comment by a-parent** [comment]
I believe this is due to a browser setting, would be nice to have the module override that setting

**Comment by krbz999** [comment]
Yes, the button font size is relative and can be configured in the core settings. I should probably just hardcode these to `9px`.
