### ISSUE TITLE
When going from normal to advantage/disadvantage, the 2 d20s get added together

### ISSUE THREAD

**Issue by JenniferPylko** [krbz999/foundryvtt-retroactive-advantage-5e#4]
![image](https://github.com/krbz999/foundryvtt-retroactive-advantage-5e/assets/3450413/af9a9187-5681-4c5e-ba63-bfdcb875eaa5)

this only occurs when normal is initially selected, then you select advantage or disadvantage. going from advantage to disadvantage or the other way around works correctly. this occurs in a brand new world with no other modules enabled.

foundry version: 12.324

d&d 5e version: 3.2.0

**Comment by krbz999** [comment]
haha woops, `Die#roll` is async now!
